spring.application.name=cpuschedulervisualization

#MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cpuscheduler?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = l1l1
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
